### ISSUE TITLE
Restore page width after adding table body

### ISSUE THREAD

**Issue by joadr** [voilab/voilab-pdf-table#1]
I noticed that if I add text to the pdf after a table. The text is put like it was in the last column.

To avoid this, you should add something like:
 ```javascript
self.pdf.x = self.pdf.page.margins.left
```
right before this line:
https://github.com/voilab/voilab-pdf-table/blob/master/voilab-table.js#L724

**Comment by tafel** [comment]
Thanks for your input. I'm adding some small fixes right now, so I will add yours too.

**Comment by garciamarco33** [comment]
Hey, you didn't add that fix right ? I'm having the same problem

**Comment by tafel** [comment]
That's right, I prefer not doing anything after the process has finished, so you can whatever you want the way you want after `addBody`.

So you have two options:
1. if you use pdf-table at one place only, just reinit `pdf.x` after `table.addBody()`
2. if you use pdf-table at multiple place, create a plugin that listen the `body-added` event (`table.onBodyAdded(fn)`) and reinitialize the x pos at the place you want on your page
