### ISSUE TITLE
Table not displaying cells with a value of 0

### ISSUE THREAD

**Issue by njeri-ngigi** [voilab/voilab-pdf-table#25]
### Steps to reproduce:
- pass data with values of 0 to table.addBody()
```
table.addBody([
            {description: 'Product 1', quantity: 0, price: 20.10, total: 20.10},
            {description: 'Product 2', quantity: 0, price: 4.00, total: 16.00},
            {description: 'Product 3', quantity: 0, price: 17.85, total: 35.70}
        ]);
```
 - The cells for quantity are empty
![image](https://user-images.githubusercontent.com/28973383/54702475-febbea00-4b47-11e9-9cef-f0c81e9c87a6.png)

- with quantity set to 10, 20, 30, here's the PDF:
![image](https://user-images.githubusercontent.com/28973383/54702547-20b56c80-4b48-11e9-866c-4362137ccb4b.png)

**Is this a bug? Does it have a work-around?**

**Comment by Drieger** [comment]
I think the problem is in this line of code

https://github.com/voilab/voilab-pdf-table/blob/fa1f0f30031efa72c534b88a58dd36f14f114945/voilab-table.js#L91

While it is not fixed! You might try to pass values as strings, or provide a renderer to handle this case.

**Comment by tafel** [comment]
Please try with new version 0.5.0
