### ISSUE TITLE
How to set header font style as bold for the header of the table

### ISSUE THREAD

**Issue by suraboy** [voilab/voilab-pdf-table#34]
table
        .addPlugin(new (require('voilab-pdf-table/plugins/fitcolumn'))({
            column: 'created_date'
        }))
        .setColumnsDefaults({
            headerBorder: 'B', align: 'right',padding:[5,0,5,0],hight:50
        })
        .addColumns(setColumns(doc))
        // add events (here, we draw headers on each new page)
        .onPageAdded(function (tb) {
            tb.addHeader();
        });

**Comment by suraboy** [comment]
i set font default to bold  and render data to regular
{
            id: 'created_date',
            header: 'Created Date',
            width: 30,
            align: 'left',
            renderer: function (tb, data) {
                doc.font(regular);
                return toBuddhistYear(moment(data.created_date).locale('th'), 'DD MMM YY');
            }
}

**Comment by RSPaul** [comment]
I have tried this:

renderer: function (tb, data) {
`.setColumnsDefaults({
                headerBorder: ['L','T','B','R'],
                align: 'center',
                padding: [5, 0, 5, 5],
                headerPadding: [15, 0, 5, 5],
                valign: 'center',
                lineGap: 3.1,
                border: ['L','T','B','R'],
                renderer : function (tb, data) {
                    tb.pdf.font('Helvetica-Bold');
                    return data;
                }
            })`
But this is changing the font style for all the rows as well, I want only for header:
`renderer : function (tb, data) {
                    tb.pdf.font('Helvetica-Bold');
                    return data;
                }`

**Comment by RSPaul** [comment]
`.onHeaderAdd(function(tb, data) {
         tb.pdf.font('Helvetica-Bold');
  })`

Same issue using the above function, changing font style for the whole document.
