### ISSUE TITLE
Cannot create property '_renderedContent' on string '['

### ISSUE THREAD

**Issue by nishant-techforceglobal** [voilab/voilab-pdf-table#39]
Hi,
I have implemented the voilab-pdf-table table in my project

I need to pass dynamic rows in to `table.addBody(response);`
I have declared `let response;`
than i have `response = JSON.stringify(result);`
got the response JSON value 

> [{"name":"LAN CABLE","brandName":"HP","modelNo":"8989","serialNo":"","purchaseDate":"01-29-2020","status":"Replacement Request","companyName":"Test"},{"name":"USB KeyBoard","brandName":"HP","modelNo":"B1","serialNo":"B1","purchaseDate":"01-10-2020","status":"Assigned","companyName":"Test"},{"name":"Laptop","brandName":"DELL","modelNo":"","serialNo":"","purchaseDate":"09-23-2020","status":"Assigned","companyName":"Amazon"},{"name":"Laptop","brandName":"HP","modelNo":"","serialNo":"","purchaseDate":"10-06-2020","status":"Pending","companyName":"Flipkart"},{"name":"Laptop","brandName":"COMPAQ","modelNo":"ASSCewgvdb","serialNo":"","purchaseDate":"10-05-2020","status":"New","companyName":"World Link"},{"name":"Wireless mouse","brandName":"HP","modelNo":"","serialNo":"","purchaseDate":"10-12-2020","status":"New","companyName":"Earth Syscom"}]

Now please anyone suggest why i am facing the below Error

`TypeError: Cannot create property '_renderedContent' on string '['
    at setRowHeight (***\node_modules\voilab-pdf-table\voilab-table.js:182:30)`

**Comment by tafel** [comment]
Hello, `table.addBody()` needs an javascript array, and not a string.
With `JSON.stringify`, it's a string you give to the method.

Try to directely pass `response` to the method, or `JSON.parse(response)` if `response` is a string.

**Comment by nishant-techforceglobal** [comment]
Thank you @tafel for help
