### ISSUE TITLE
How i can add boder to cell

### ISSUE THREAD

**Issue by deblis** [voilab/voilab-pdf-table#5]
The module works super well, I need to add border to each cell. How can I do this??
This only work for the header.??
 .setColumnsDefaults({
      headerBorder: ['L','T','B','R'],
      align: 'center'
    })

**Comment by tafel** [comment]
Hi, did you try with `border` ?

```
.setColumnsDefaults({
    headerBorder: ['L','T','B','R'],
    border: ['L','T','B','R'],
    align: 'center'
})
```

**Comment by deblis** [comment]
Thanksss, it's work. 

Many Reagards
